package guillaume_braibant.webservices_k8s_springboot_apachecxf.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://webservices-k8s-springboot-apachecxf.guillaume-braibant/interfaces", name = "sayHelloInterface")
@XmlSeeAlso({guillaume_braibant.webservices_k8s_springboot_apachecxf.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SayHelloInterface {

    @WebMethod
    @WebResult(name = "response", targetNamespace = "", partName = "response")
    public java.lang.String sayHello(
        @WebParam(partName = "username", name = "username", targetNamespace = "")
        guillaume_braibant.webservices_k8s_springboot_apachecxf.types.FullName username
    );
}
