
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package guillaume_braibant.webservices_k8s_springboot_apachecxf.endpoints;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Logger;

import org.apache.cxf.annotations.SchemaValidation;
import org.springframework.stereotype.Service;

import guillaume_braibant.webservices_k8s_springboot_apachecxf.interfaces.SayHelloInterface;
import guillaume_braibant.webservices_k8s_springboot_apachecxf.types.FullName;

/**
 * This class was generated by Apache CXF 3.2.7 Generated source version: 3.2.7
 */

@javax.jws.WebService(serviceName = "sayHelloService", portName = "sayHelloInterface", targetNamespace = "http://webservices-k8s-springboot-apachecxf.guillaume-braibant/interfaces", wsdlLocation = "classpath:services.wsdl", endpointInterface = "guillaume_braibant.webservices_k8s_springboot_apachecxf.interfaces.SayHelloInterface")
@Service
@SchemaValidation
public class SayHelloServiceImpl implements SayHelloInterface {
    private static final Logger LOG = Logger.getLogger(SayHelloServiceImpl.class.getName());

    /**
     * The name of the host that executes the application.
     */
    private String hostname;

    /**
     * Default constructor for the SayHelloServiceImpl class
     */
    public SayHelloServiceImpl() 
    {    
        try 
        {
            this.hostname = InetAddress.getLocalHost().getHostName();
        } 
        catch (UnknownHostException e) 
        {
            this.hostname = "Localhost";
        }
    }

    /**
     * Say hello to the user
     */
    public String sayHello (FullName username) 
    {
        LOG.info("Executing operation sayHello");
        return "Hello " + username.getFirstName() + " " + username.getLastName() + " from " + this.hostname;
    }
}
